### ISSUE TITLE
`node-pre-gyp install --fallback-to-build` error on node v6.9.0

### ISSUE THREAD

**Issue by kazaff** [node-inspector/v8-profiler#101]
```
3557 verbose stack Error: @risingstack/v8-profiler@5.7.0 install: `node-pre-gyp install --fallback-to-build`
3557 verbose stack Exit status 126
3557 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v6.9.0/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
3557 verbose stack     at emitTwo (events.js:106:13)
3557 verbose stack     at EventEmitter.emit (events.js:191:7)
3557 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v6.9.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
3557 verbose stack     at emitTwo (events.js:106:13)
3557 verbose stack     at ChildProcess.emit (events.js:191:7)
3557 verbose stack     at maybeClose (internal/child_process.js:877:16)
3557 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by kazaff** [comment]
my os is centos

**Comment by HustStevenZ** [comment]
You may post on the wrong repo.  @risingstack/v8-profiler@5.7.0 should be located on https://github.com/RisingStack/v8-profiler.git. Meanwhile, I tested both 5.6.5 and 5.7.0. They both can be built correctly on node 6.9.4. Maybe you need 'npm install -g nan' and give another try.
