### ISSUE TITLE
npm install v8-profiler - Doesn't work

### ISSUE THREAD

**Issue by jucajuca** [node-inspector/v8-profiler#104]
Hello 

I'm getting following error when trying to install v8-profiler.
THX

```
@fileserver:/var/www/sharelatex# npm install v8-profiler
npm WARN lifecycle v8-profiler@5.6.5~preinstall: cannot run in wd %s %s (wd=%s) v8-profiler@5.6.5 node -e 'process.exit(0)' /var/www/sharelatex/node_modules/.staging/v8-profiler-0bc57285

> v8-profiler@5.6.5 install /var/www/sharelatex/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.6.5/node-v48-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.6.5 and node@6.9.5 (node-v48 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.9.5"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/sharelatex/node_modules/v8-profiler/.node-gyp"
make: Entering directory '/var/www/sharelatex/node_modules/v8-profiler/build'
make: *** No rule to make target '../.node-gyp/6.9.5/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/var/www/sharelatex/node_modules/v8-profiler/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.38-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/var/www/sharelatex/node_modules/v8-profiler/build/profiler/v5.6.5/node-v48-linux-arm/profiler.node" "--module_name=profiler" "--module_path=/var/www/sharelatex/node_modules/v8-profiler/build/profiler/v5.6.5/node-v48-linux-arm"
gyp ERR! cwd /var/www/sharelatex/node_modules/v8-profiler
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/www/sharelatex/node_modules/v8-profiler/build/profiler/v5.6.5/node-v48-linux-arm/profiler.node --module_name=profiler --module_path=/var/www/sharelatex/node_modules/v8-profiler/build/profiler/v5.6.5/node-v48-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/www/sharelatex/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.38-v7+
node-pre-gyp ERR! command "/usr/bin/nodejs" "/var/www/sharelatex/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /var/www/sharelatex/node_modules/v8-profiler
node-pre-gyp ERR! node -v v6.9.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/www/sharelatex/node_modules/v8-profiler/build/profiler/v5.6.5/node-v48-linux-arm/profiler.node --module_name=profiler --module_path=/var/www/sharelatex/node_modules/v8-profiler/build/profiler/v5.6.5/node-v48-linux-arm' (1)
npm WARN sharelatex@0.1.4 No repository field.
npm WARN sharelatex@0.1.4 No license field.
npm ERR! Linux 4.4.38-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "v8-profiler"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! v8-profiler@5.6.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-profiler@5.6.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-profiler
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/sharelatex/npm-debug.log
```

**Comment by VLZH** [comment]
Same problem

**Comment by jucajuca** [comment]
Yes, the problem here were the access rights to the directory /var/www. I copied everything into the home folder and then I ran npm.

**Comment by marcosleonel** [comment]
I tried to install with yarn and got the same problem.

`error /Users/marcosleonel/Documents/Dev/suno-analitica-backend/node_modules/v8-profiler: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /Users/marcosleonel/Documents/Dev/suno-analitica-backend/node_modules/v8-profiler
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@10.6.0 | darwin | x64
node-pre-gyp info check checked for "/Users/marcosleonel/Documents/Dev/suno-analitica-backend/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64/profiler.
node" (not found)
node-pre-gyp http GET https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.7.0 and node@10.6.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-darwin-x64.tar.gznode-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-darwin-x64.tar.gznode-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.7.0 and node@10.6.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http Connection closed while downloading tarball file
gypgyp info it worked if it ends with ok
 info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.6.0 | darwin | x64
gyp info using node-gyp@3.6.2
gyp info using node@10.6.0 | darwin | x64
gyp info ok
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.6.0 | darwin | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.6.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/marcosleonel/Documents/Dev/suno-analitica-backend/node_modules/v8-profiler/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp gypinfo spawn args    '-I',
gyp info spawn args   '/Users/marcosleonel/.node-gyp/10.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
infogyp  spawninfo /usr/bin/python
 spawn args   '-Dnode_root_dir=/Users/marcosleonel/.node-gyp/10.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gypgyp  info infospawn args    '-Dnode_lib_file=/Users/marcosleonel/.node-gyp/10.6.0/<(target_arch)/node.lib',
spawn argsgyp [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
 info spawn args   '-Dmodule_root_dir=/Users/marcosleonel/Documents/Dev/suno-analitica-backend/node_modules/v8-profiler',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn argsgyp    '--no-parallel',
infogyp  spawn argsinfo   'binding.gyp',
 gypspawn args    '--generator-output',
infogyp  spawn argsinfo   '-f',
 gypspawn args    'build',
infogyp  spawn argsinfo   'make',
 gypspawn args    '-Goutput_dir=.' ]
info spawn args   '-I',
gyp info spawn args   '/Users/marcosleonel/Documents/Dev/suno-analitica-backend/node_modules/v8-profiler/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/marcosleonel/.node-gyp/10.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/marcosleonel/.node-gyp/10.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/marcosleonel/.node-gyp/10.6.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/marcosleonel/Documents/Dev/suno-analitica-backend/node_modules/v8-profiler',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance


xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance


gyp info ok
gyp info ok
gypgyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.6.0 | darwin | x64
 info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.6.0 | darwin | x64
gypgyp  infoinfo  spawnspawn make
 make
gypgyp  infoinfo  spawn argsspawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
 [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/profiler/src/profiler.o
  CXX(target) Release/obj.target/profiler/src/profiler.o
rm: ./Release/.deps/Release/obj.target/profiler/src/profiler.o.d.raw: No such file or directory
make: *** [Release/obj.target/profiler/src/profiler.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/marcosleonel/Documents/Dev/suno-analitica-backend/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64/profiler.node" "--module_name=profiler" "--module_path=/Users/marcosleonel/Documents/Dev/suno-analitica-backend/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64"
gyp ERR! cwd /Users/marcosleonel/Documents/Dev/suno-analitica-backend/node_modules/v8-profiler
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/marcosleonel/Documents/Dev/suno-analitica-backend/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/marcosleonel/Documents/Dev/suno-analitica-backend/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/marcosleonel/Documents/Dev/suno-analitica-backend/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 15.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/marcosleonel/Documents/Dev/suno-analitica-backend/node_modules/v8-profiler/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/marcosleonel/Documents/Dev/suno-analitica-backend/node_modules/v8-profiler
node-pre-gyp ERR! node -v v10.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/marcosleonel/Documents/Dev/suno-analitica-backend/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/marcosleonel/Documents/Dev/suno-analitica-backend/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64' (1)
  CXX(target) Release/obj.target/profiler/src/cpu_profiler.o
../src/cpu_profiler.cc:35:32: warning: 'GetCpuProfiler' is deprecated [-Wdeprecated-declarations]
    v8::Isolate::GetCurrent()->GetCpuProfiler()->StartProfiling(title, recsamples);
                               ^
/Users/marcosleonel/.node-gyp/10.6.0/include/node/v8.h:7355:30: note: 'GetCpuProfiler' has been explicitly marked deprecated here
                CpuProfiler* GetCpuProfiler());
                             ^
../src/cpu_profiler.cc:54:42: warning: 'GetCpuProfiler' is deprecated [-Wdeprecated-declarations]
    profile = v8::Isolate::GetCurrent()->GetCpuProfiler()->StopProfiling(title);
                                         ^
/Users/marcosleonel/.node-gyp/10.6.0/include/node/v8.h:7355:30: note: 'GetCpuProfiler' has been explicitly marked deprecated here
                CpuProfiler* GetCpuProfiler());
                             ^
../src/cpu_profiler.cc:64:32: warning: 'GetCpuProfiler' is deprecated [-Wdeprecated-declarations]
    v8::Isolate::GetCurrent()->GetCpuProfiler()->SetSamplingInterval(info[0]->Uint32Value());
                               ^
/Users/marcosleonel/.node-gyp/10.6.0/include/node/v8.h:7355:30: note: 'GetCpuProfiler' has been explicitly marked deprecated here
                CpuProfiler* GetCpuProfiler());
                             ^
3 warnings generated.
  CXX(target) Release/obj.target/profiler/src/cpu_profile.o
  CXX(target) Release/obj.target/profiler/src/cpu_profile_node.o
  CXX(target) Release/obj.target/profiler/src/heap_profiler.o
../src/heap_profiler.cc:35:18: error: no matching constructor for initialization of 'v8::TryCatch'
        TryCatch try_catch;
                 ^
/Users/marcosleonel/.node-gyp/10.6.0/include/node/v8.h:8394:12: note: candidate constructor not viable: requires single argument 'isolate', but no arguments were provided
  explicit TryCatch(Isolate* isolate);
           ^
/Users/marcosleonel/.node-gyp/10.6.0/include/node/v8.h:8514:3: note: candidate constructor not viable: requires 1 argument, but 0 were provided
  TryCatch(const TryCatch&) = delete;
  ^
1 error generated.
make: *** [Release/obj.target/profiler/src/heap_profiler.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/marcosleonel/Documents/Dev/suno-analitica-backend/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64/profiler.node" "--module_name=profiler" "--module_path=/Users/marcosleonel/Documents/Dev/suno-analitica-backend/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64"
gyp ERR! cwd /Users/marcosleonel/Documents/Dev/suno-analitica-backend/node_modules/v8-profiler
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok`
