### ISSUE TITLE
npm install v8-profiler - Doesn't work

### ISSUE THREAD

**Issue by darkterra** [node-inspector/v8-profiler#105]
```> v8-profiler@5.6.5 preinstall /home/ubuntu/workspace/node_modules/.staging/v8-profiler-010bb724
> node -e 'process.exit(0)'


> v8-profiler@5.6.5 install /home/ubuntu/workspace/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.6.5/node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.6.5 and node@7.7.3 (node-v51 ABI) (falling back to source compile with node-gyp) 
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/home/ubuntu/workspace/node_modules/v8-profiler/build'
  CXX(target) Release/obj.target/profiler/src/profiler.o
  CXX(target) Release/obj.target/profiler/src/cpu_profiler.o
  CXX(target) Release/obj.target/profiler/src/cpu_profile.o
  CXX(target) Release/obj.target/profiler/src/cpu_profile_node.o
  CXX(target) Release/obj.target/profiler/src/heap_profiler.o
../src/heap_profiler.cc: In member function ‘virtual v8::ActivityControl::ControlOption nodex::ActivityControlAdapter::ReportProgressValue(int, int)’:
../src/heap_profiler.cc:35:18: warning: ‘v8::TryCatch::TryCatch()’ is deprecated (declared at /home/ubuntu/.node-gyp/7.7.3/include/node/v8.h:7616): Use isolate version [-Wdeprecated-declarations]
         TryCatch try_catch;
                  ^
  CXX(target) Release/obj.target/profiler/src/heap_snapshot.o
../src/heap_snapshot.cc: In static member function ‘static Nan::NAN_GETTER_RETURN_TYPE nodex::Snapshot::GetRoot(v8::Local<v8::String>, Nan::NAN_GETTER_ARGS_TYPE)’:
../src/heap_snapshot.cc:46:46: error: ‘class v8::Object’ has no member named ‘GetHiddenValue’
       info.GetReturnValue().Set(info.This()->GetHiddenValue(__root));
                                              ^
../src/heap_snapshot.cc:50:20: error: ‘class v8::Object’ has no member named ‘SetHiddenValue’
       info.This()->SetHiddenValue(__root, _root);
                    ^
make: *** [Release/obj.target/profiler/src/heap_snapshot.o] Error 1
make: Leaving directory `/home/ubuntu/workspace/node_modules/v8-profiler/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v7.7.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.8.8-c9
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v7.7.3/bin/node" "/home/ubuntu/.nvm/versions/node/v7.7.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/ubuntu/workspace/node_modules/v8-profiler/build/profiler/v5.6.5/node-v51-linux-x64/profiler.node" "--module_name=profiler" "--module_path=/home/ubuntu/workspace/node_modules/v8-profiler/build/profiler/v5.6.5/node-v51-linux-x64"
gyp ERR! cwd /home/ubuntu/workspace/node_modules/v8-profiler
gyp ERR! node -v v7.7.3
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/ubuntu/.nvm/versions/node/v7.7.3/bin/node /home/ubuntu/.nvm/versions/node/v7.7.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ubuntu/workspace/node_modules/v8-profiler/build/profiler/v5.6.5/node-v51-linux-x64/profiler.node --module_name=profiler --module_path=/home/ubuntu/workspace/node_modules/v8-profiler/build/profiler/v5.6.5/node-v51-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ubuntu/workspace/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.8.8-c9
node-pre-gyp ERR! command "/home/ubuntu/.nvm/versions/node/v7.7.3/bin/node" "/home/ubuntu/workspace/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ubuntu/workspace/node_modules/v8-profiler
node-pre-gyp ERR! node -v v7.7.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok 
Failed to execute '/home/ubuntu/.nvm/versions/node/v7.7.3/bin/node /home/ubuntu/.nvm/versions/node/v7.7.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ubuntu/workspace/node_modules/v8-profiler/build/profiler/v5.6.5/node-v51-linux-x64/profiler.node --module_name=profiler --module_path=/home/ubuntu/workspace/node_modules/v8-profiler/build/profiler/v5.6.5/node-v51-linux-x64' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN sinon-chai@2.8.0 requires a peer of sinon@>=1.4.0 <2 but none was installed.
npm WARN The package pm2 is included as both a dev and production dependency.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler@5.6.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-profiler@5.6.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-profiler
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2017-03-18T16_40_09_067Z-debug.log```

**Comment by hustxiaoc** [comment]
Please try `v8-profiler@5.7.0` , should work now!
