### ISSUE TITLE
Unable to download v8-profiler build info from aws

### ISSUE THREAD

**Issue by crazyyi** [node-inspector/v8-profiler#117]
I ran a `yarn add v8-profiler` on OSX but I get this error:

```
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.34
node-pre-gyp info using node@8.1.0 | darwin | x64
node-pre-gyp info check checked for "/node_projects/project/node_modules/v8-profiler/build/profiler/v5.7.0/node-v57-darwin-x64/profiler.node" (not found)
node-pre-gyp http GET https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-darwin-x64.tar.gz
node-pre-gyp http 404 https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.7.0 and node@8.1.0 (node-v57 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/node_projects/project/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
node-pre-gyp ERR! stack     at emitOne (events.js:115:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:7)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:195:12)
node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:366:16)
node-pre-gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:102:11)
node-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:161:9)
node-pre-gyp ERR! System Darwin 14.5.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/8.1.0_1/bin/node" "/node_projects/project/node_modules/v8-profiler/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /node_projects/project/node_modules/v8-profiler
node-pre-gyp ERR! node -v v8.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok 
Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
```

**Comment by dalinwangsonos** [comment]
I ran into the same exact problem with Node 8.x. Is there a solution to this?

**Comment by marko-jankovic** [comment]
I'm using `@risingstack/v8-profiler` and it works fine on node v6 and v7. On v8 it works only for mac, but on linux I get similar errors:

node-pre-gyp ERR! Tried to download(404): https://oss.risingstack.com/repo/v1/@risingstack/profiler/dist/v5.7.11/node-v57-linux-x64.tar.gz 

node-pre-gyp ERR! Pre-built binaries not found for @risingstack/v8-profiler@5.7.11 and node@8.1.4 (node-v57 ABI) (falling back to source compile with node-gyp)

**Comment by jorgenavarrochavez** [comment]
I have same error with x86_64 GNU/Linux.
node-pre-gyp ERR! Tried to download(404): https://oss.risingstack.com/repo/v1/@risingstack/profiler/dist/v5.7.10/node-v57-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for @risingstack/v8-profiler@5.7.10 and node@8.10.0 (node-v57 ABI) (falling back to source compile with node-gyp)
