### ISSUE TITLE
v8-profiler doesn't work : Cannot find module './build/profiler/v5.7.0/node-v57-win32-ia32/profiler.node'

### ISSUE THREAD

**Issue by shitada** [node-inspector/v8-profiler#120]
I installed v8-profiler on azure app service on windows by referring this document.
https://docs.microsoft.com/en-us/azure/app-service/app-service-web-nodejs-best-practices-and-troubleshoot-guide

I wrote a code and accessed top page, I got this error on logging-errors.txt.

Thu Dec 07 2017 03:03:39 GMT+0000 (Coordinated Universal Time): Application has thrown an uncaught exception and is terminated:
Error: Cannot find module './build/profiler/v5.7.0/node-v57-win32-ia32/profiler.node'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\v8-profiler\v8-profiler.js:2:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

I digged into directories and found that. 
D:\home\site\wwwroot\node_modules\v8-profiler\build\profiler\v5.7.0\node-v48-win32-ia32\profiler.node
There is no node-v57-win32-ia32 folder.

Does anyone know how to fix it?

**Comment by tankala** [comment]
Hi,

I got the similar problem.
"Error: Cannot find module './build/profiler/v5.7.0/node-v48-linux-x64/profiler.node' on 5.7.0
After spending some time with that figured out that I am using **node v7.10.1** at the time of installation and at the time of running the application I am using **node v6.11.4**.

I uninstalled v8-profiler and used **node v6.11.4** using **nvm** then installed v8-profiler again. Problem solved.
