### ISSUE TITLE
npm install -g v8-profiler error 

### ISSUE THREAD

**Issue by shivam04** [node-inspector/v8-profiler#131]
npm install -g v8-profiler
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

> v8-profiler@5.7.0 preinstall /usr/local/lib/node_modules/v8-profiler
> node -e 'process.exit(0)'

> v8-profiler@5.7.0 install /usr/local/lib/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v72-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.7.0 and node@12.6.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/var/root/Library/Caches/node-gyp/12.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/v8-profiler/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/v8-profiler/.node-gyp'
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/12.6.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/v8-profiler/build/profiler/v5.7.0/node-v72-darwin-x64/profiler.node" "--module_name=profiler" "--module_path=/usr/local/lib/node_modules/v8-profiler/build/profiler/v5.7.0/node-v72-darwin-x64"
gyp ERR! cwd /usr/local/lib/node_modules/v8-profiler
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/12.6.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/v8-profiler/build/profiler/v5.7.0/node-v72-darwin-x64/profiler.node --module_name=profiler --module_path=/usr/local/lib/node_modules/v8-profiler/build/profiler/v5.7.0/node-v72-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/v8-profiler/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/12.6.0/bin/node" "/usr/local/lib/node_modules/v8-profiler/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/v8-profiler
node-pre-gyp ERR! node -v v12.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/12.6.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/v8-profiler/build/profiler/v5.7.0/node-v72-darwin-x64/profiler.node --module_name=profiler --module_path=/usr/local/lib/node_modules/v8-profiler/build/profiler/v5.7.0/node-v72-darwin-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler@5.7.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-profiler@5.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2019-08-22T08_58_17_407Z-debug.log

**Comment by Muyixone** [comment]
Hello Shivam04, I know it's been a long time, but were you able to resolve this issue, and if yes, can remember how you did it? Would appreciate. Thanks
