### ISSUE TITLE
install fail

### ISSUE THREAD

**Issue by cool-firer** [node-inspector/v8-profiler#135]
On mac node v10.16.0, npm install v8-profiler fail，is this package  still maintained?

demondeMacBook-Pro:v8profile demon$ npm i -g node-gyp
/Users/demon/.nvm/versions/node/v10.16.0/bin/node-gyp -> /Users/demon/.nvm/versions/node/v10.16.0/lib/node_modules/node-gyp/bin/node-gyp.js
+ node-gyp@6.1.0
added 101 packages from 67 contributors in 37.682s
demondeMacBook-Pro:v8profile demon$ npm install v8-profiler
npm WARN deprecated hawk@3.1.3: This version has been deprecated. Please upgrade to the latest version to get the best features, bug fixes, and security patches.
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

> v8-profiler@5.7.0 preinstall /Users/demon/Desktop/own/perftest/v8profile/node_modules/v8-profiler
> node -e 'process.exit(0)'

> v8-profiler@5.7.0 install /Users/demon/Desktop/own/perftest/v8profile/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.7.0 and node@10.16.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.7.0 and node@10.16.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
gypgyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
 WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gypgyp  WARNWARN  downloaddownload NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
 NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gypgyp  WARN WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/profiler/src/profiler.o
  CXX(target) Release/obj.target/profiler/src/profiler.o
  CXX(target) Release/obj.target/profiler/src/cpu_profiler.o
sed: ./Release/.deps/Release/obj.target/profiler/src/profiler.o.d.raw: No such file or directory
rm: ./Release/.deps/Release/obj.target/profiler/src/profiler.o.d.raw: No such file or directory
make: *** [Release/obj.target/profiler/src/profiler.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/demon/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/Users/demon/.nvm/versions/node/v10.16.0/bin/node" "/Users/demon/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/demon/Desktop/own/perftest/v8profile/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64/profiler.node" "--module_name=profiler" "--module_path=/Users/demon/Desktop/own/perftest/v8profile/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64"
gyp ERR! cwd /Users/demon/Desktop/own/perftest/v8profile/node_modules/v8-profiler
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/demon/.nvm/versions/node/v10.16.0/bin/node /Users/demon/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/demon/Desktop/own/perftest/v8profile/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/demon/Desktop/own/perftest/v8profile/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/demon/Desktop/own/perftest/v8profile/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 18.5.0
node-pre-gyp ERR! command "/Users/demon/.nvm/versions/node/v10.16.0/bin/node" "/Users/demon/Desktop/own/perftest/v8profile/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/demon/Desktop/own/perftest/v8profile/node_modules/v8-profiler
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/Users/demon/.nvm/versions/node/v10.16.0/bin/node /Users/demon/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/demon/Desktop/own/perftest/v8profile/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/demon/Desktop/own/perftest/v8profile/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64' (1)
../src/cpu_profiler.cc:2:10: fatal error: 'cpu_profile.h' file not found: Failed to exec install script
#include "cpu_profile.h"
         ^~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/profiler/src/cpu_profiler.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/demon/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/Users/demon/.nvm/versions/node/v10.16.0/bin/node" "/Users/demon/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/demon/Desktop/own/perftest/v8profile/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64/profiler.node" "--module_name=profiler" "--module_path=/Users/demon/Desktop/own/perftest/v8profile/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64"
gyp ERR! cwd /Users/demon/Desktop/own/perftest/v8profile/node_modules/v8-profiler
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN co-mocha@1.2.2 requires a peer of mocha@>=1.18 <6 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler@5.7.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-profiler@5.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/demon/.npm/_logs/2020-01-17T13_45_15_696Z-debug.log

**Comment by jusebin** [comment]
I got the same :(

**Comment by cool-firer** [comment]
this project is dead, right?

**Comment by Dartv** [comment]
Same here. Any workarounds?
Edit: following this guide fixed it for me https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md#Solutions
