### ISSUE TITLE
dead?

### ISSUE THREAD

**Issue by Esqarrouth** [node-inspector/v8-profiler#137]
is this project dead?

**Comment by gustawdaniel** [comment]
I can't install on node: `v12.14.1`.

This project was mentioned in article

https://medium.com/@petar.koretic/profiling-slow-node-js-apps-using-v8-profiler-5d44c07bf09f

when node 10 is described.

Example of error

```
 Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v72-linux-x64.tar.gz 
```

**Comment by nerkn** [comment]
cant install using npm on node 14.15 

npm ERR! /home/n/.cache/node-gyp/14.15.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
npm ERR! ../../nan/nan_object_wrap.h:65:61:   required from here
npm ERR! /home/n/.cache/node-gyp/14.15.1/include/node/v8.h:10867:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
npm ERR! make: *** [profiler.target.mk:119: Release/obj.target/profiler/src/cpu_profiler.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Linux 5.4.0-70-generic
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/mnt/control/node_modules/v8-profiler/build/profiler/v5.7.0/node-v83-linux-x64/profiler.node" "--module_name=profiler" "--module_path=/control/node_modules/v8-profiler/build/profiler/v5.7.0/node-v83-linux-x64"
npm ERR! gyp ERR! cwd /mnt/control/node_modules/v8-profiler
npm ERR! gyp ERR! node -v v14.15.1
npm ERR! gyp ERR! node-gyp -v v7.1.2

**Comment by mmigdol** [comment]
Hope this helps others finding their way here.  [Here](https://github.com/hyj1991/v8-profiler-next) is a fork that works all the way through Node 18.
