### ISSUE TITLE
node --debug ... : Cannot find module './profiler'

### ISSUE THREAD

**Issue by abarriere** [node-inspector/v8-profiler#35]
I have an error when executing node --debug ...
module.js:340
    throw err;
          ^
Error: Cannot find module './profiler'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\PJ_SoLoMo\source\geojon_in\osm\node_modules\mongosm\node_modules\v8-profiler\v8-profiler.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by 3y3** [comment]
Fixed long time ago
