### ISSUE TITLE
unable to install on Ubuntu 14.04 x64

### ISSUE THREAD

**Issue by dlewanda** [node-inspector/v8-profiler#38]
I am trying to install v8-profiler, but running into this error:

npm http GET https://registry.npmjs.org/v8-profiler
npm http 304 https://registry.npmjs.org/v8-profiler

> v8-profiler@4.0.1 install /home/dlewanda/Documents/switchboard/cloud-control/speed-server/node_modules/v8-profiler
> node-gyp rebuild

Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
...
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm ERR! v8-profiler@4.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-profiler@4.0.1 install script.
npm ERR! This is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "v8-profiler"
...
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
...

Please advise as to how to proceed.

**Comment by rektide** [comment]
Hi. I'm on Debian, & getting this error. Below is the log of `node-gyp configure` from a checkout of v8-profiler.

```
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.12.0 | linux | x64
child_process: customFds option is deprecated, use stdio instead.
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/src/archive/v8-profiler/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/rektide/.node-gyp/0.12.0/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/rektide/.node-gyp/0.12.0',
gyp info spawn args   '-Dmodule_root_dir=/usr/local/src/archive/v8-profiler',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.18.3
gyp ERR! command "node" "/usr/local/bin/node-gyp" "configure"
gyp ERR! cwd /usr/local/src/archive/v8-profiler
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
```

`apt-cache show gyp` identifies a version `0.1~svn1729-3` on this Debian/Testing box.

Checking out and build/installing gyp ended up being easy. Once I upgraded gyp, v8-profiler installed. I can now run `node-inspector` on this box.

**Comment by ChrisRus** [comment]
Similar issues (thanks for posting on Twitter). I reverted to Node 0.11.3, and upgraded the node-gyp package globally. Rebuilt/re-installed Node.js and then node-inspector from npm. Some errors. It is loading, **and** I can see my source code w/ --break-brk. Console nag about updating to Node 11.3 not displayed (FWIW latest 9 from #master atop Node 0.12.0 came up but couldn't detect Node version, and would not break correctly on entry w/visibility to my source).

**Comment by deltreey** [comment]
getting a similar error on raspbian.  Not sure if this is a perfect match here, but I didn't think it was worthy of a new bug.  Looks like the problem I'm having is that it assumes pre-built binaries in a relative directory for node-gyp.  Even though node-gyp is installed globally on my system, it doesn't seem to care.

```
root@honeycomb:/home/administrator/tmp# /opt/node/bin/npm install v8-profiler
npm http GET https://registry.npmjs.org/v8-profiler
npm http 304 https://registry.npmjs.org/v8-profiler

> v8-profiler@5.2.9 preinstall /home/administrator/tmp/node_modules/v8-profiler
>

npm http GET https://registry.npmjs.org/node-pre-gyp
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/node-pre-gyp

> v8-profiler@5.2.9 install /home/administrator/tmp/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://node-inspector.s3.amazonaws.com/profiler/v5.2.9/node-v0.11.12-linux-arm.tar.gz
node-pre-gyp http 404 https://node-inspector.s3.amazonaws.com/profiler/v5.2.9/node-v0.11.12-linux-arm.tar.gz
node-pre-gyp http Pre-built binary not available for your system, looked for https://node-inspector.s3.amazonaws.com/profiler/v5.2.9/node-v0.11.12-linux-arm.tar.gz (falling back to source compile with node-gyp)
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.11.12"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/administrator/tmp/node_modules/v8-profiler/.node-gyp"
gyp http GET http://nodejs.org/dist/v0.11.12/node-v0.11.12.tar.gz
gyp http 200 http://nodejs.org/dist/v0.11.12/node-v0.11.12.tar.gz
make: Entering directory '/home/administrator/tmp/node_modules/v8-profiler/build'
make: *** No rule to make target '../.node-gyp/0.11.12/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/home/administrator/tmp/node_modules/v8-profiler/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/node-v0.11.12-linux-arm-pi/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:107:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1045:12)
gyp ERR! System Linux 3.18.11-v7+
gyp ERR! command "/opt/node-v0.11.12-linux-arm-pi/bin/node" "/opt/node-v0.11.12-linux-arm-pi/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/administrator/tmp/node_modules/v8-profiler/build/profiler/v5.2.9/node-v0.11.12-linux-arm/profiler.node" "--module_name=profiler" "--module_path=/home/administrator/tmp/node_modules/v8-profiler/build/profiler/v5.2.9/node-v0.11.12-linux-arm"
gyp ERR! cwd /home/administrator/tmp/node_modules/v8-profiler
gyp ERR! node -v v0.11.12
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/opt/node-v0.11.12-linux-arm-pi/bin/node /opt/node-v0.11.12-linux-arm-pi/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/administrator/tmp/node_modules/v8-profiler/build/profiler/v5.2.9/node-v0.11.12-linux-arm/profiler.node --module_name=profiler --module_path=/home/administrator/tmp/node_modules/v8-profiler/build/profiler/v5.2.9/node-v0.11.12-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/administrator/tmp/node_modules/v8-profiler/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:107:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:991:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1058:5)
node-pre-gyp ERR! System Linux 3.18.11-v7+
node-pre-gyp ERR! command "node" "/home/administrator/tmp/node_modules/v8-profiler/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/administrator/tmp/node_modules/v8-profiler
node-pre-gyp ERR! node -v v0.11.12
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok
Failed to execute '/opt/node-v0.11.12-linux-arm-pi/bin/node /opt/node-v0.11.12-linux-arm-pi/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/administrator/tmp/node_modules/v8-profiler/build/profiler/v5.2.9/node-v0.11.12-linux-arm/profiler.node --module_name=profiler --module_path=/home/administrator/tmp/node_modules/v8-profiler/build/profiler/v5.2.9/node-v0.11.12-linux-arm' (1)
npm ERR! v8-profiler@5.2.9 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler@5.2.9 install script.
npm ERR! This is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.18.11-v7+
npm ERR! command "/opt/node/bin/node" "/opt/node/bin/npm" "install" "v8-profiler"
npm ERR! cwd /home/administrator/tmp
npm ERR! node -v v0.11.12
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/administrator/tmp/npm-debug.log
npm ERR! not ok code 0
root@honeycomb:/home/administrator/tmp#
```
