### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by samccone** [node-inspector/v8-profiler#46]
This is from an install of node-inspector on debian wheezy VM.

The pertinent info from error log is below

```
7993 verbose unsafe-perm in lifecycle false
7994 info postinstall ws@0.4.32
7995 info v8-profiler@5.2.1 Failed to exec install script
7996 verbose unsafe-perm in lifecycle false
7997 verbose unlock done using /tmp/package-npm-build20141217-12426-3tlgda/npm_cache/_locks/v8-profiler-f2f667534b8d1b43.lock for /tmp/package-npm-staging20141217-12426-ku306y/usr/local/lib/node_modules/node-inspector/node_modules/v8-profiler
7998 verbose unlock done using /tmp/package-npm-build20141217-12426-3tlgda/npm_cache/_locks/ws-1832b606207cfbd5.lock for /tmp/package-npm-staging20141217-12426-ku306y/usr/local/lib/node_modules/node-inspector/node_modules/ws
7999 info v8-debug@0.3.1 Failed to exec install script
8000 verbose unlock done using /tmp/package-npm-build20141217-12426-3tlgda/npm_cache/_locks/v8-debug-1a2e513680e6a1ee.lock for /tmp/package-npm-staging20141217-12426-ku306y/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug
8001 verbose about to build /tmp/package-npm-staging20141217-12426-ku306y/usr/local/lib/node_modules/node-inspector
8002 verbose unlock done using /tmp/package-npm-build20141217-12426-3tlgda/npm_cache/_locks/node-inspector-a32a6c47c0cbf1ab.lock for /tmp/package-npm-staging20141217-12426-ku306y/usr/local/lib/node_modules/node-inspector
8003 verbose stack Error: v8-profiler@5.2.1 install: `node-pre-gyp install --fallback-to-build`
8003 verbose stack Exit status 127
8003 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:212:16)
8003 verbose stack     at ChildProcess.emit (events.js:98:17)
8003 verbose stack     at maybeClose (child_process.js:755:16)
8003 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:822:5)
8004 verbose pkgid v8-profiler@5.2.1
8005 verbose cwd /home/sam
8006 error Linux 3.14-0.bpo.1-amd64
8007 error argv "node" "/usr/bin/npm" "install" "node_modules/node-inspector/" "--cache" "/tmp/package-npm-build20141217-12426-3tlgda/npm_cache" "--loglevel" "warn" "--global" "true" "--prefix" "/tmp/package-npm-staging20141217-12426-ku306y/usr/local"
8008 error node v0.10.29
8009 error npm  v2.1.5
8010 error code ELIFECYCLE
8011 error v8-profiler@5.2.1 install: `node-pre-gyp install --fallback-to-build`
8011 error Exit status 127
8012 error Failed at the v8-profiler@5.2.1 install script.
8012 error This is most likely a problem with the v8-profiler package,
8012 error not with npm itself.
```

Let me know if I can provide any more info!

**Comment by 3y3** [comment]
I added some fixes to v8-profiler and v8-debug. Also I added prebuild binaries for Linux and OSX.
Please try to reinstall node-inspector now.

**Comment by samccone** [comment]
Will do, thanks so much!
