### ISSUE TITLE
Error: module did not self-register [iojs 1.4.1]

### ISSUE THREAD

**Issue by gm112** [node-inspector/v8-profiler#54]
Pesky iojs user here. Version 1.2.x seemed to reproduce this problem as well. Basically, when trying to include v8-profiler in any nodejs app, the module fails to load.

Node Inspector is now available from http://127.0.0.1:8080/debug?port=5858
Debugging `server.js`

Debugger listening on port 5858
module.js:339
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Module.require (module.js:349:17)
    at require (module.js:368:17)
    at Object.<anonymous> (C:\source\trunk\Proxy\node_modules\v8-pro
filer\v8-profiler.js:4:15)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Module.require (module.js:349:17)
    at require (module.js:368:17)
    at Object.<anonymous> (C:\source\trunk\Proxy\server.js:11:16)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Module.runMain [as _onTimeout] (module.js:485:10)
    at Timer.listOnTimeout (timers.js:88:15)

**Comment by gm112** [comment]
Bump. Affects 1.4.3 as well. Seems this is a Windows-bound issue.

**Comment by 3y3** [comment]
This is an iojs issue https://github.com/iojs/io.js/issues/751

**Comment by gm112** [comment]
Ah, I see. Thanks for pointing that out!

**Comment by 3y3** [comment]
Fixed with latest 1.x and 2.x versions
