### ISSUE TITLE
node-pre-gyp angry

### ISSUE THREAD

**Issue by bmeck** [node-inspector/v8-profiler#72]
apparently node-pre-gyp demands more config
```
node-pre-gyp --nodedir=~/Documents/io.js/ rebuild
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.4.2
node-pre-gyp info using node@3.0.1-pre | darwin | x64
node-pre-gyp ERR! clean error 
node-pre-gyp ERR! stack Error: v8-profiler package.json is not node-pre-gyp ready:
node-pre-gyp ERR! stack package.json must declare 'binary.template'
node-pre-gyp ERR! stack     at validate_config (/usr/local/lib/node_modules/node-pre-gyp/lib/util/versioning.js:79:25)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/usr/local/lib/node_modules/node-pre-gyp/lib/util/versioning.js:95:5)
node-pre-gyp ERR! stack     at clean (/usr/local/lib/node_modules/node-pre-gyp/lib/clean.js:15:16)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as clean] (/usr/local/lib/node_modules/node-pre-gyp/lib/node-pre-gyp.js:53:37)
node-pre-gyp ERR! stack     at run (/usr/local/lib/node_modules/node-pre-gyp/bin/node-pre-gyp:72:30)
node-pre-gyp ERR! stack     at doNTCallback0 (node.js:407:9)
node-pre-gyp ERR! stack     at process._tickCallback (node.js:336:13)
node-pre-gyp ERR! stack     at Function.Module.runMain (module.js:473:11)
node-pre-gyp ERR! stack     at startup (node.js:117:18)
node-pre-gyp ERR! stack     at node.js:952:3
node-pre-gyp ERR! System Darwin 14.4.0
node-pre-gyp ERR! command "/usr/local/bin/iojs" "/usr/local/bin/node-pre-gyp" "--nodedir=~/Documents/io.js/" "rebuild"
node-pre-gyp ERR! cwd /Users/bradleymeck/Documents/test/v8-profiler
node-pre-gyp ERR! node -v v3.0.1-pre
node-pre-gyp ERR! node-pre-gyp -v v0.4.2
node-pre-gyp ERR! not ok 
```

**Comment by 3y3** [comment]
node-pre-gyp -v v0.4.2?

Why you use so outdated version?

**Comment by bmeck** [comment]
@3y3 `npm -g i node-pre-gyp` gave me that version, today with `node` at `3.0.1-pre`
