### ISSUE TITLE
failed to install with npm3

### ISSUE THREAD

**Issue by valery-barysok** [node-inspector/v8-profiler#75]
```cmd
> v8-profiler@5.3.0 preinstall C:\Users\valery\AppData\Roaming\npm\node_modules\.staging\v8-profiler-6edec23615d37dd4f6c2de1976766e62
>  


> v8-profiler@5.3.0 install C:\Users\valery\AppData\Roaming\npm\node_modules\v8-profiler
> node-pre-gyp install --fallback-to-build

gyp: C:\Users\valery\.node-gyp\4.0.0\common.gypi not found (cwd: C:\Users\valery\AppData\Roaming\npm\node_modules\v8-profiler) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\valery\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "D:\\work\\tools\\nodejs-4.0.0-x64\\node.exe" "C:\\Users\\valery\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\valery\\AppData\\Roaming\\npm\\node_modules\\v8-profiler\\build\\profiler\\v5.3.0\\node-v46-win32-x64\\profiler.node" "--module_name=profiler" "--module_path=C:\\Users\\valery\\AppData\\Roaming\\npm\\node_modules\\v8-profiler\\build\\profiler\\v5.3.0\\node-v46-win32-x64" "--msvs_version=2015"
gyp ERR! cwd C:\Users\valery\AppData\Roaming\npm\node_modules\v8-profiler
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'D:\work\tools\nodejs-4.0.0-x64\node.exe C:\Users\valery\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\valery\AppData\Roaming\npm\node_modules\v8-profiler\build\profiler\v5.3.0\node-v46-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\valery\AppData\Roaming\npm\node_modules\v8-profiler\build\profiler\v5.3.0\node-v46-win32-x64 --msvs_version=2015' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\valery\AppData\Roaming\npm\node_modules\v8-profiler\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10240
node-pre-gyp ERR! command "D:\\work\\tools\\nodejs-4.0.0-x64\\node.exe" "C:\\Users\\valery\\AppData\\Roaming\\npm\\node_modules\\v8-profiler\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\valery\AppData\Roaming\npm\node_modules\v8-profiler
node-pre-gyp ERR! node -v v4.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.10
node-pre-gyp ERR! not ok 
Failed to execute 'D:\work\tools\nodejs-4.0.0-x64\node.exe C:\Users\valery\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\valery\AppData\Roaming\npm\node_modules\v8-profiler\build\profiler\v5.3.0\node-v46-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\valery\AppData\Roaming\npm\node_modules\v8-profiler\build\profiler\v5.3.0\node-v46-win32-x64 --msvs_version=2015' (1)
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "D:\\work\\tools\\nodejs-4.0.0-x64\\node.exe" "C:\\Users\\valery\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "v8-profiler" "-g"
npm ERR! node v4.0.0
npm ERR! npm  v3.2.2
npm ERR! code ELIFECYCLE

npm ERR! v8-profiler@5.3.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-profiler@5.3.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\test\npm-debug.log
```

**Comment by valery-barysok** [comment]
it works when i switch to npm2

**Comment by llambda** [comment]
Same problem on Fedora 23 / Node 5 / npm 3.4.
