### ISSUE TITLE
Can't install 5.3.2 on OS X, rollback to 5.3.1 works well

### ISSUE THREAD

**Issue by nenemoianemoi** [node-inspector/v8-profiler#81]
OS X
npm version 3.3.3
node version 4.1.0

```
$ npm install v8-profiler

> v8-profiler@5.3.2 preinstall /Users/roman/dev/myapp/node_modules/.staging/v8-profiler-53b5108765897882753580a19fe16368
>


> bufferutil@1.2.1 install /Users/roman/dev/myapp/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node

> utf-8-validate@1.2.1 install /Users/roman/dev/myapp/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> v8-profiler@5.3.2 install /Users/roman/dev/myapp/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

module.js:338
    throw err;
    ^

Error: Cannot find module 'nopt'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/roman/dev/myapp/node_modules/node-pre-gyp/lib/node-pre-gyp.js:14:12)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
nan@2.0.9 node_modules/v8-profiler/node_modules/nan -> node_modules/nan
node-pre-gyp@0.6.10 node_modules/v8-profiler/node_modules/node-pre-gyp -> node_modules/node-pre-gyp
- minimist@0.0.8 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/mkdirp/node_modules/minimist
- mkdirp@0.5.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/mkdirp
- abbrev@1.0.7 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/nopt/node_modules/abbrev
- nopt@3.0.3 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/nopt
- ansi@0.3.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/ansi
- delegates@0.1.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/delegates
- core-util-is@1.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/node_modules/core-util-is
- inherits@2.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/node_modules/inherits
- isarray@0.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/node_modules/isarray
- string_decoder@0.10.31 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/node_modules/string_decoder
- readable-stream@1.1.13 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream
- are-we-there-yet@1.0.4 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet
- has-unicode@1.0.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/has-unicode
- lodash._basetostring@3.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.pad/node_modules/lodash._basetostring
- lodash.repeat@3.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.pad/node_modules/lodash._createpadding/node_modules/lodash.repeat
- lodash._createpadding@3.6.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.pad/node_modules/lodash._createpadding
- lodash.pad@3.1.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.pad
- lodash._basetostring@3.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padleft/node_modules/lodash._basetostring
- lodash.repeat@3.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padleft/node_modules/lodash._createpadding/node_modules/lodash.repeat
- lodash._createpadding@3.6.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padleft/node_modules/lodash._createpadding
- lodash.padleft@3.1.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padleft
- lodash._basetostring@3.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padright/node_modules/lodash._basetostring
- lodash.repeat@3.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padright/node_modules/lodash._createpadding/node_modules/lodash.repeat
- lodash._createpadding@3.6.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padright/node_modules/lodash._createpadding
- lodash.padright@3.1.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padright
- gauge@1.2.2 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge
- npmlog@1.2.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/npmlog
- deep-extend@0.2.11 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/rc/node_modules/deep-extend
- ini@1.3.4 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/rc/node_modules/ini
- minimist@1.2.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/rc/node_modules/minimist
- strip-json-comments@0.1.3 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/rc/node_modules/strip-json-comments
- rc@1.1.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/rc
- aws-sign2@0.5.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/aws-sign2
- core-util-is@1.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/core-util-is
- inherits@2.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/inherits
- isarray@0.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/isarray
- process-nextick-args@1.0.3 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/process-nextick-args
- string_decoder@0.10.31 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/string_decoder
- util-deprecate@1.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/util-deprecate
- readable-stream@2.0.2 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/bl/node_modules/readable-stream
- bl@1.0.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/bl
- caseless@0.11.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/caseless
- delayed-stream@1.0.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/combined-stream/node_modules/delayed-stream
- combined-stream@1.0.5 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/combined-stream
- extend@3.0.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/extend
- forever-agent@0.6.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/forever-agent
- async@1.4.2 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/form-data/node_modules/async
- bluebird@2.10.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/bluebird
- ansi-styles@2.1.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/ansi-styles
- escape-string-regexp@1.0.3 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/escape-string-regexp
- ansi-regex@2.0.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/has-ansi/node_modules/ansi-regex
- has-ansi@2.0.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/has-ansi
- ansi-regex@2.0.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/strip-ansi/node_modules/ansi-regex
- strip-ansi@3.0.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/strip-ansi
- supports-color@2.0.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/supports-color
- chalk@1.1.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/chalk
- graceful-readlink@1.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/commander/node_modules/graceful-readlink
- commander@2.8.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/commander
- generate-function@2.0.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-function
- is-property@1.0.2 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property
- generate-object-property@1.2.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property
- jsonpointer@2.0.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/jsonpointer
- xtend@4.0.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/xtend
- is-my-json-valid@2.12.2 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid
- har-validator@1.8.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator
- hoek@2.14.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/hawk/node_modules/hoek
- boom@2.8.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/hawk/node_modules/boom
- cryptiles@2.0.5 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/hawk/node_modules/cryptiles
- sntp@1.0.9 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/hawk/node_modules/sntp
- hawk@3.1.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/hawk
- asn1@0.1.11 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/http-signature/node_modules/asn1
- assert-plus@0.1.5 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/http-signature/node_modules/assert-plus
- ctype@0.5.3 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/http-signature/node_modules/ctype
- http-signature@0.11.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/http-signature
- isstream@0.1.2 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/isstream
- json-stringify-safe@5.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/json-stringify-safe
- mime-db@1.18.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/mime-types/node_modules/mime-db
- mime-types@2.1.6 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/mime-types
- form-data@1.0.0-rc3 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/form-data
- node-uuid@1.4.3 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/node-uuid
- oauth-sign@0.8.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/oauth-sign
- qs@4.0.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/qs
- stringstream@0.0.4 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/stringstream
- tough-cookie@2.0.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/tough-cookie
- tunnel-agent@0.4.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request/node_modules/tunnel-agent
- request@2.61.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/request
- wrappy@1.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/node_modules/inflight/node_modules/wrappy
- inherits@2.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/node_modules/inherits
- balanced-match@0.2.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/balanced-match
- concat-map@0.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map
- brace-expansion@1.1.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion
- minimatch@2.0.10 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/node_modules/minimatch
- wrappy@1.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/node_modules/once/node_modules/wrappy
- once@1.3.2 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/node_modules/once
- inflight@1.0.4 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/node_modules/inflight
- path-is-absolute@1.0.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob/node_modules/path-is-absolute
- glob@5.0.14 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/rimraf/node_modules/glob
- rimraf@2.4.3 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/rimraf
- semver@5.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/semver
- debug@0.7.4 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/debug
- inherits@2.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/fstream-ignore/node_modules/inherits
- lru-cache@2.6.5 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/fstream-ignore/node_modules/minimatch/node_modules/lru-cache
- sigmund@1.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/fstream-ignore/node_modules/minimatch/node_modules/sigmund
- minimatch@0.2.14 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/fstream-ignore/node_modules/minimatch
- graceful-fs@3.0.8 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/fstream/node_modules/graceful-fs
- inherits@2.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/fstream/node_modules/inherits
- graceful-fs@1.2.3 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/graceful-fs
- once@1.1.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/once
- core-util-is@1.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/readable-stream/node_modules/core-util-is
- inherits@2.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/readable-stream/node_modules/inherits
- isarray@0.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/readable-stream/node_modules/isarray
- string_decoder@0.10.31 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/readable-stream/node_modules/string_decoder
- readable-stream@1.0.33 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/readable-stream
- rimraf@2.2.8 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/rimraf
- fstream@0.1.31 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/fstream
- fstream-ignore@0.0.7 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/fstream-ignore
- inherits@2.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/tar/node_modules/inherits
- block-stream@0.0.8 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/tar/node_modules/block-stream
- tar@0.1.20 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/tar
- uid-number@0.0.3 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/uid-number
- tar-pack@2.0.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar-pack
- graceful-fs@3.0.8 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar/node_modules/fstream/node_modules/graceful-fs
- inherits@2.0.1 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar/node_modules/inherits
- fstream@1.0.7 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar/node_modules/fstream
- block-stream@0.0.8 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar/node_modules/block-stream
- tar@2.2.0 node_modules/v8-profiler/node_modules/node-pre-gyp/node_modules/tar
/Users/roman/dev/myapp
└─┬ ws@0.8.0
  ├─┬ bufferutil@1.2.1
  │ └── bindings@1.2.1
  └── utf-8-validate@1.2.1

npm WARN ENOENT ENOENT: no such file or directory, open '/Users/roman/dev/myapp/package.json'
npm WARN EPACKAGEJSON /Users/roman/dev/myapp No description
npm WARN EPACKAGEJSON /Users/roman/dev/myapp No repository field.
npm WARN EPACKAGEJSON /Users/roman/dev/myapp No README data
npm WARN EPACKAGEJSON /Users/roman/dev/myapp No license field.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/4.1.0/bin/node" "/usr/local/bin/npm" "install" "v8-profiler"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.3
npm ERR! code ELIFECYCLE

npm ERR! v8-profiler@5.3.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler@5.3.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/roman/dev/myapp/channel/npm-debug.log
```

**Comment by nenemoianemoi** [comment]
strange, but i'm try second time, and now it successfully installed

```
$ npm install v8-profiler@5.3.2
...
[v8-profiler] Success: ...
```
