### ISSUE TITLE
Not escaping characters within path.

### ISSUE THREAD

**Issue by mbarrus73** [node-inspector/v8-profiler#87]
I got the following error when trying to do npm install.  Once I renamed my directory to not have the parentheses, the installation worked.

I put all my development within dropbox.  and dropbox sometimes adds (personal) when you have also linked a business account.

I fixed the drop box name by doing the following

rm -f Dropbox && mv "Dropbox (Personal)" Dropbox && ln -s Dropbox "Dropbox (Personal)"

But the error still exists when characters aren't escaped properly.

=================================================
node-pre-gyp install --fallback-to-build

  CXX(target) Release/obj.target/profiler/src/profiler.o
  CXX(target) Release/obj.target/profiler/src/cpu_profiler.o
  CXX(target) Release/obj.target/profiler/src/cpu_profile.o
  CXX(target) Release/obj.target/profiler/src/cpu_profile_node.o
  CXX(target) Release/obj.target/profiler/src/heap_profiler.o
  CXX(target) Release/obj.target/profiler/src/heap_snapshot.o
  CXX(target) Release/obj.target/profiler/src/heap_output_stream.o
  CXX(target) Release/obj.target/profiler/src/heap_graph_node.o
  CXX(target) Release/obj.target/profiler/src/heap_graph_edge.o
  SOLINK_MODULE(target) Release/profiler.node
  COPY /Users/mbarrus/Dropbox (Personal)/Developer/ho4_tracking/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.12/node-v47-darwin-x64/profiler.node
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `printf '%s\n' 'cmd_/Users/mbarrus/Dropbox?(Personal)/Developer/ho4_tracking/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.12/node-v47-darwin-x64/profiler.node := rm -rf "/Users/mbarrus/Dropbox (Personal)/Developer/ho4_tracking/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.12/node-v47-darwin-x64/profiler.node" && cp -af "Release/profiler.node" "/Users/mbarrus/Dropbox (Personal)/Developer/ho4_tracking/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.12/node-v47-darwin-x64/profiler.node"' > ./Release/.deps//Users/mbarrus/Dropbox?(Personal)/Developer/ho4_tracking/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.12/node-v47-darwin-x64/profiler.node.d'
make: *** [/Users/mbarrus/Dropbox (Personal)/Developer/ho4_tracking/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.12/node-v47-darwin-x64/profiler.node] Error 2
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/mbarrus/Dropbox (Personal)/Developer/ho4_tracking/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.12/node-v47-darwin-x64/profiler.node" "--module_name=profiler" "--module_path=/Users/mbarrus/Dropbox (Personal)/Developer/ho4_tracking/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.12/node-v47-darwin-x64"

**Comment by 3y3** [comment]
That you can propose to fix this permanently?
