### ISSUE TITLE
Error in requiring profiler.node in module.js with electron

### ISSUE THREAD

**Issue by aharringtonaviata** [node-inspector/v8-profiler#95]
node version: 5.8.0
npm version: 3.7.3
v8-profiler version: 5.6.5
electron-prebuilt version: 1.3.3
electron-builder version: 5.24.0
electron-packager version: 7.5.1

Whenever just trying to do a require in my javascript file I get the following error:

`Error: Cannot find module './build/profiler/v5.6.5/node-v49-linux-x64/profiler.node'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (/home/user/repo/node_modules/electron-prebuilt/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/user/repo/node_modules/v8-profiler/v8-profiler.js:2:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gambit/aviata/powerengage-electron-prototype/app/main.js:28:18)`

This is with trying to add the profiler to an app using electron, more specifically electron builder/packager. looks like my process.versions.modules is returning 49 when trying to run the app, but whenever I check it in the Node REPL I get back a 47. Any ideas why this is happening?

**Comment by jrieken** [comment]
@aharringtonaviata I have created a fork that makes this work on electron but it removes the rebuilt binary feature. See https://github.com/jrieken/v8-profiler/tree/fixRequireCall

**Comment by tankala** [comment]
Hi,

I got the similar problem.
"Error: Cannot find module './build/profiler/v5.7.0/node-v48-linux-x64/profiler.node' on 5.7.0
After spending some time with that figured out that I am using **node v7.10.1** at the time of installation and at the time of running the application I am using **node v6.11.4**.

I uninstalled v8-profiler and used **node v6.11.4** using **nvm** then installed v8-profiler again. Problem solved.
